# Generated by Django 4.1.3 on 2023-05-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_tages'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='post-first', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
